version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:15
    container_name: contacto-postgres
    restart: always
    environment:
      POSTGRES_DB: contacto_dev
      POSTGRES_USER: contacto_user
      POSTGRES_PASSWORD: contacto_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
